### LLAMA Service Discovery Server Settings ###

# Service discovery API URL, example http://somehost.com:8081
server: http://127.0.0.1


### Probe Registration Settings ###

# How long before service discovery removes an enpoint that has not
# checked in. This value is in seconds and is set by default to the 
# value listed below.
keepalive: 300

# Group probe register's as
group: default

# Port LLAMA probes are running on, 8100 is the default - !!! not working at this time !!!
#port: 8100

# Tags to register, "key: value, key: value". Please note "," are not valid here.
tags: [ hostname: las1.something.com, src_short: las1, city: Las Vegas, state: Nevada ]

# Tell the server what your IP address should be, if none is given the server will try to figure this out for you
#ip: 127.0.0.1

### Application Debugging ###

# Debug logging level, True or False
verbose: False
